spring:
  devtools.livereload.enabled: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: 1234567890
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate:
      sql: debug
      type.descriptor.sql.basic-binder: trace
